generator:
  worker-size: 10

spring:
  datasource:
    url: jdbc:h2:mem:coupon;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    platform: h2
    username: sa
    driverClassName: org.h2.Driver
    schema: classpath:/h2/schema.sql
    data: classpath:/h2/data.sql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
  h2:
    console:
      enabled: true
      path: /h2
  servlet:
    multipart:
      max-file-size: 50MB #CSV 파일 업로드 50메가
      max-request-size: 100MB
  thymeleaf:
    cache: false
    template-resolver-order: 0
logging:
  level:
    org.springframework.jdbc: INFO
