CREATE TABLE COUPON (
    ID VARCHAR(40) PRIMARY KEY,
    ASSIGN_USER_ID VARCHAR(30),
    STATE VARCHAR(20),
    CREATE_DATE_TIME TIMESTAMP,
    ASSIGNED_DATE_TIME TIMESTAMP,
    USE_DATE_TIME TIMESTAMP,
    EXPIRATION_DATE  DATE
);


